apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modelop-center
    service: engine-jit
  name: engine-jit
spec:
  selector:
    matchLabels:
      app: modelop-center
      service: engine-jit
  template:
    metadata:
      labels:
        app: modelop-center
        service: engine-jit
      name: engine-jit
    spec:
      containers:
      - env:
        - name: MODELOP_ENGINE_HOSTNAME
          value: engine-jit
        - name: MODELOP_ENGINE_NAME
          value: engine-jit
        - name: MODELOP_EUREKA_HOSTNAME
          value: registry
        - name: MODELOP_EUREKA_PORT
          value: '8761'
        - name: MODELOP_LOGSTASH_LOCATION
          value: whitetail:9003
        - name: MODELOP_GATEWAY_LOCATION
          value: gateway:8090
        - name: MODELOP_RUNTIME_INITIAL_TAGS
          value: MYSQL,RHEL8,PY36,ENGINE-JIT
        - name: MODELOP_RUNTIME_GROUP
          value: modelop
        - name: MODELOP_OAUTH_SCOPE
          value: ''
        - name: MODELOP_OAUTH_SERVER_URL
          value: https://external.pf.modelop.center/as/token.oauth2
        - name: MODELOP_OAUTH_CLIENT_ID
          value: modelop-runtime
        - name: MODELOP_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: RUNTIME_CLIENT_SECRET
              name: moc-credentials
        - name: spring.application.name
          value: engine-jit
        image: modelop/runtime:dev-rhel8
        imagePullPolicy: Always
        name: engine-jit
        ports:
        - containerPort: 8003
          name: runtime-http
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /tmp
          name: temp-dir
        - mountPath: /modelop/certs
          name: cert-files
        - mountPath: /config
          name: s3-config
      hostname: engine-jit
      imagePullSecrets:
      - name: modelop-regcreds
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: temp-dir
      - configMap:
          name: cert-configmap
        name: cert-files
      - name: s3-config
        secret:
          secretName: engine-jit-s3-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: modelop-center
    service: engine-jit
  name: engine-jit
spec:
  ports:
  - name: runtime-http
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: modelop-center
    service: engine-jit
  sessionAffinity: None
  type: ClusterIP